AllCops:
  NewCops: enable
  SuggestExtensions: false

  Exclude:
    - 'vendor/**/*'
    - 'bundle/**/*'
    - 'gems/**/*'
    - '**/gems/**'
    - '**/.bundle/**'

# Disattiva i cop Metrics più invasivi
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

# Disattiva Naming/FileName se non vuoi forzare snake_case
Naming/FileName:
  Enabled: false

# Tutti i cop nuovi che avevi già abilitato restano gestiti da NewCops: enable