name: 🔐 Security Audit

on:
  schedule:
    - cron: '0 4 * * *' # Ogni giorno alle 4:00 UTC
  workflow_dispatch:     # Possibilità di lanciarlo manualmente

jobs:
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    name: Audit Ruby ${{ matrix.ruby-version }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: 📦 Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: 🧪 Run bundler-audit
        run: |
          gem install bundler-audit
          bundler-audit update
          bundler-audit check --verbose
